const destinations = [
 {id:"lonavala",name:"Lonavala",location:"Maharashtra, India",cost:8500,minDays:2,maxDays:4,moods:["Adventure","Escape","Relax"],travellers:["Friends","Couple","Family"],preferences:["Nature","Mountains","Adventure","Photography"],image:"https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=85",duration:"3 Days",transport:2200,stay:3000,food:1800,activities:1500,description:"Green hills, misty viewpoints and easy weekend trails tucked into the Western Ghats.",bestTime:"October – February",things:["Tiger Point","Rajmachi Fort","Bhushi Dam","Karla Caves"]},
 {id:"mahabaleshwar",name:"Mahabaleshwar",location:"Maharashtra, India",cost:9000,minDays:2,maxDays:5,moods:["Relax","Escape","Explore"],travellers:["Friends","Couple","Family"],preferences:["Nature","Mountains","Food","Photography"],image:"https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1000&q=85",duration:"3 Days",transport:2400,stay:3200,food:1900,activities:1500,description:"Cool mountain air, strawberry farms and panoramic valleys make this an easy slow escape.",bestTime:"October – June",things:["Arthur's Seat","Venna Lake","Mapro Garden","Pratapgad"]},
 {id:"alibaug",name:"Alibaug",location:"Maharashtra, India",cost:7800,minDays:2,maxDays:4,moods:["Relax","Escape"],travellers:["Friends","Couple","Family"],preferences:["Beaches","Food","Photography","Nature"],image:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=85",duration:"3 Days",transport:1800,stay:3000,food:1800,activities:1200,description:"A breezy coastal reset with beaches, old forts and seafood by the sea.",bestTime:"November – February",things:["Alibaug Beach","Kolaba Fort","Kihim Beach","Kashid"]},
 {id:"goa",name:"Goa",location:"Goa, India",cost:14500,minDays:3,maxDays:7,moods:["Relax","Explore","Escape"],travellers:["Friends","Couple","Solo"],preferences:["Beaches","Food","Nightlife","Photography"],image:"https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1000&q=85",duration:"5 Days",transport:4500,stay:5000,food:3000,activities:2000,description:"Beach mornings, local cafés, old neighbourhoods and evenings that stretch a little longer.",bestTime:"November – February",things:["Palolem","Fontainhas","Dudhsagar","Anjuna"]},
 {id:"manali",name:"Manali",location:"Himachal Pradesh, India",cost:18500,minDays:4,maxDays:8,moods:["Adventure","Escape","Explore"],travellers:["Friends","Couple","Solo"],preferences:["Mountains","Nature","Adventure","Photography"],image:"https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1000&q=85",duration:"5 Days",transport:6500,stay:5500,food:3000,activities:3500,description:"Mountain roads, pine forests and high-altitude adventures for a longer reset.",bestTime:"March – June",things:["Solang Valley","Old Manali","Rohtang region","Hadimba Temple"]},
 {id:"jaipur",name:"Jaipur",location:"Rajasthan, India",cost:11500,minDays:3,maxDays:6,moods:["Explore","Escape"],travellers:["Friends","Couple","Family","Solo"],preferences:["Culture","Food","Photography"],image:"https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1000&q=85",duration:"4 Days",transport:3500,stay:4000,food:2200,activities:1800,description:"Fort walls, old markets, architecture and a food scene built for wandering.",bestTime:"October – March",things:["Amber Fort","Hawa Mahal","City Palace","Jantar Mantar"]},
 {id:"udaipur",name:"Udaipur",location:"Rajasthan, India",cost:13000,minDays:3,maxDays:6,moods:["Relax","Explore","Escape"],travellers:["Couple","Friends","Family"],preferences:["Culture","Food","Photography"],image:"https://images.unsplash.com/photo-1602643163983-ed0babc39797?auto=format&fit=crop&w=1000&q=85",duration:"4 Days",transport:4000,stay:4700,food:2400,activities:1900,description:"Lakeside evenings, old-city lanes and palaces reflected in calm water.",bestTime:"October – March",things:["Lake Pichola","City Palace","Sajjangarh","Bagore Ki Haveli"]},
 {id:"munnar",name:"Munnar",location:"Kerala, India",cost:14000,minDays:3,maxDays:7,moods:["Relax","Escape","Adventure"],travellers:["Couple","Friends","Family"],preferences:["Nature","Mountains","Photography","Food"],image:"https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=85",duration:"4 Days",transport:4500,stay:4300,food:2600,activities:2600,description:"Tea-covered hills, winding roads and cool green landscapes in Kerala's highlands.",bestTime:"September – March",things:["Tea Museum","Top Station","Mattupetty","Eravikulam"]}
];
